# -*- coding: utf-8 -*-
"""0 ao Python Dia5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13duDHrOtVRU1mzQII45A6gLYM0XuJp40
"""

!pip install -q matplotlib  #instalando biblioteca de gerar graficos
from matplotlib import pyplot as plt  #renomeando a blibioteca importada
import csv

def obter_dados():
  with open('CarRentalData.csv') as f:
    return [dado_carro for dado_carro in csv.DictReader(f)]

def contar_carros_eletricos_por_ano(dados):
  # o objetivo é conseguir um dicionario nesse formato:
  # {'2015': 100, '2016': 120}
  cont = {}

  for carro in dados:
    if carro['fuelType'] == 'ELECTRIC':
      ano = carro['vehicle.year']

      qtd = cont.get(ano, 0) + 1
      cont.update({ano: qtd})
      
      # print(cont)
  return cont

def pegar_dados_de_tuplas(lista_de_dados, posicao):
  valores = []

  for valor in lista_de_dados:
    valores.append(valor[posicao])
  return valores

dados_carros = obter_dados()
carros_eletricos_por_ano = contar_carros_eletricos_por_ano(dados_carros)

#Ordena os dados para o gráfico
carros_ordenados = sorted(carros_eletricos_por_ano.items()) 

#Separação dos dados em duas listas: ano e quantidade
anos = pegar_dados_de_tuplas(carros_ordenados, 0)
quantidades = pegar_dados_de_tuplas(carros_ordenados, 1)

#Criação do gráfico
plt.xlabel('Anos')
plt.ylabel('Quantidade de Veiculos Elétricos')
plt.plot(anos, quantidades) #Grafico de linhas
plt.bar(anos, quantidades) #Grafico de barras
plt.savefig('carElecPerAno.png')